export const KEYWORDS = [
  'for the love of barbara allen',
  'golden hope christmas',
  'a elkins never surrenders',
  'a gent from bear creek',
  'a gent from bear creek',
  'a gent from the pecos',
  'a man-eating jeopard',
  'a new game for costigan',
  'a ring-tailed tornado',
  'a thunder of trumpets',
  'a two-fisted santa claus',
  'a witch shall be born',
  'alleys of darkness',
  'alleys of peril',
  'alleys of treachery',
  'almuric',
  'beyond the black river',
  'black canaan',
  'black colossus',
  'black country',
  'black hound of death',
  'black talons',
  'black vulmea\'s vengeance',
  'black wind blowing',
  'blades for france',
  'blood of the gods',
  'boot-hill payoff',
  'breed of battle',
  'by this axe i rule!',
  'casonetto\'s last song',
  'champ of the forecastle',
  'circus fists',
  'collected juvenilia',
  'college socks',
  'cupid from bear creek',
  'cupid vs. pollux',
  'dark shanghai',
  'delenda est',
  'dermod\'s bane',
  'dig me no grave',
  'drums of the sunset',
  'evil deeds at red cougar',
  'exile of atlantis',
  'fangs of gold',
  'fighting nerves',
  'fighting nerves',
  'fist and fang',
  'fists of the desert',
  'fists of the revolution',
  'flying knuckles',
  'gates of empire',
  'general ironfist',
  'gents on the lynch',
  'gold from tatary',
  'graveyard rats',
  'guns of the mountains',
  'hawk of the hills',
  'hawks of outremer',
  'hawks over egypt',
  'high horse rampage',
  'in the forest of villefére',
  'iron shadows in the moon',
  'iron-clad fists',
  'kelly the conjure-man',
  'kid galahad',
  'kings of the night',
  'knife-river prodigal',
  'lord of samarcand',
  'lord of the dead',
  'men of the shadows',
  'mountain man',
  'names in the black book',
  'night of battle',
  'no cowherders wanted',
  'old garfield\'s heart',
  'out of the deep',
  'people of the dark',
  'pigeons from hell',
  'pilgrims to the pecos',
  'pistol politics',
  'queen of the black coast',
  'rattle of bones',
  'red blades of black cathay',
  'red nails',
  'red shadows',
  'restless waters',
  'rogues in the house',
  'sailor costigan and the swami',
  'sailor\'s grudge',
  'sea curse',
  'sharp\'s gun serenade',
  'she devil',
  'skull-face',
  'skulls in the stars',
  'sluggers of the beach',
  'son of the white wolf',
  'sons of the hawk',
  'spear and fang',
  'spears of clontarf',
  'spectres in the dark',
  'sword woman',
  'swords of shahrazar',
  'swords of the hills',
  'swords of the purple kingdom',
  'swords of the red brotherhood',
  'texas fists',
  'the altar and the scorpion',
  'the apache mountain war',
  'the black moon',
  'the black stone',
  'the black stranger',
  'the blood of belshazzar',
  'the blue flame of vengeance',
  'the bull dog breed',
  'the cairn on the headland',
  'the cat and the skull',
  'the challenge from beyond',
  'the children of the night',
  'the cobra in the dream',
  'the conquerin\' hero of the humbolts',
  'the curse of the golden skull',
  'the dark man',
  'the daughter of erlik khan',
  'the dead remember',
  'the destiny gorilla',
  'the devil in iron',
  'the dragon of kao tsu',
  'the dream snake',
  'the dwellers under the tomb',
  'the fearsome touch of death',
  'the feud buster',
  'the fightin\'est pair',
  'the fighting fury',
  'the fire of asshurbanipal',
  'the fire of asshurbanipal',
  'the footfalls within',
  'the frost-giant\'s daughter',
  'the garden of fear',
  'the ghost in the doorway',
  'the god in the bowl',
  'the gods of bal-sagoth',
  'the grey god passes',
  'the grisly horror',
  'the haunted hut',
  'the haunted mountain',
  'the haunter of the ring',
  'the hills of the dead',
  'the honor of the ship',
  'the hoofed thing',
  'the horror from the mound',
  'the hour of the dragon',
  'the house of arabu',
  'the house of peril',
  'the house of suspicion',
  'the hyena',
  'the iron man',
  'the isle of pirate\'s doom',
  'the jade monkey',
  'the last ride',
  'the lion of tiberias',
  'the little people',
  'the lost race',
  'the lost valley of iskander',
  'the man on the ground',
  'the man with the mystery mitts',
  'the man-eaters of zamboula',
  'the mirrors of tuzun thune',
  'the moon of skulls',
  'the noseless horror',
  'the people of the black circle',
  'the phoenix on the sword',
  'the pit of the serpent',
  'the pool of the black one',
  'the purple heart of erlik',
  'the right hand of doom',
  'the riot at cougar paw',
  'the riot of bucksnort',
  'the road of azrael',
  'the road of the eagles',
  'the road to bear creek',
  'the scalp hunter',
  'the scarlet citadel',
  'the screaming skull of silence',
  'the servants of bit-yakin',
  'the shadow kingdom',
  'the shadow of doom',
  'the shadow of the beast',
  'the shadow of the vulture',
  'the sign of the snake',
  'the silver heel',
  'the skull in the clouds',
  'the slugger\'s game',
  'the sowers of the thunder',
  'the spirit of tom molyneaux',
  'the striking of the gong',
  'the thing on the roof',
  'the tnt punch',
  'the tomb of the dragon',
  'the tomb\'s secret',
  'the tower of the elephant',
  'the trail of the blood-stained god',
  'the treasures of tartary',
  'the vale of the lost women',
  'the valley of the lost',
  'the valley of the worm',
  'the voice of death',
  'the voice of el-lil',
  'the wildcat and the star',
  'the yellow cobra',
  'three-bladed doom',
  'three-bladed doom',
  'under the baobab tree',
  'vikings of the gloves',
  'vultures of wahpeton',
  'vultures\' sanctuary',
  'war on bear creek',
  'waterfront fists',
  'while smoke rolled',
  'wild water',
  'wings in the night',
  'winner take all',
  'wolfshead',
  'worms of the earth',
  'xuthal of the dusk',
  'a dull sound as of knocking',
  'a legend of faring town',
  'a song of the naked lands',
  'a song of the race',
  'a song of the werewolf folk',
  'a thousand years ago',
  'a word from the outer dark',
  'am-ra the ta-an',
  'an echo from the iron harp',
  'an open window',
  'black harps in the hills',
  'cimmeria',
  'dead man\'s hate',
  'echoes from an anvil',
  'flint\'s passing',
  'fragment',
  'lines written in the realization that i must die',
  'moon mockery',
  'musings',
  'never beyond the beast',
  'one who comes at eventide',
  'recompense',
  'remembrance',
  'solomon kane\'s homecoming',
  'summer morn',
  'the dead slaver\'s tale',
  'the drums of pictdom',
  'the dust dance',
  'the dweller in dark valley',
  'the fear that follows',
  'the ghost kings',
  'the grim land',
  'the king and the oak',
  'the marching song of connacht',
  'the moor ghost',
  'the one black stain',
  'the outgoing of sigurd the jerusalem-farer',
  'the return of sir richard grenville',
  'the sign of the sickle',
  'the song of a mad minstrel',
  'the song of the last briton',
  'the symbol',
  'the tavern',
  'the tide',
  'timur-lang',
  'to a woman',
  'untitled',
  'untitled poem',
  'up, john kane!',
  'which will scarcely be understood',
  'the black city',
  'untitled draft',
  'untitled fragment',
  'untitled fragment',
  'untitled fragment',
  'the hyborian age',
  'notes on various peoples of the hyborian age',
  'untitled draft',
  'untitled fragment',
  'untitled synopsis',
  'untitled synopsis',
  'untitled synopsis',
  'untitled synopsis',
  'the castle of the devil',
  'the children of asshur',
  'death\'s black riders',
  'hawk of basti',
  'untitled draft',
  'untitled fragment',
  'untitled fragment',
  'wolves beyond the border',
  'mistress of death',
  'recap of harold lamb\'s the wolf chaser',
  'the slave-princess',
  'the track of bohemund',
  'untitled fragment',
  'untitled fragment',
  'untitled fragment',
  'golnar the ape',
  'the house',
  'untitled fragment',
  'bran mak morn',
  'breckinridge elkins',
  'conan',
  'cormac fitzgeoffrey',
  'cormac mac art',
  'dark agnes de chastillon',
  'el borak',
  'james allison',
  'kirby o\'donnell',
  'kull',
  'solomon kane',
  'sailor steve costigan',
  'steve harrison',
  'black vulmea',
  'red sonya of rogatino',
  'skull-face',
  'esau cairn',
];
